### ISSUE TITLE
app.php loaded too late, hence interface alias is not registered

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/twofactor_totp#17]
Core checks 2FA providers whether they are enabled for a specific users. However, this provider can not be instantiated as the alias for the ITotp interface is not registered already at that point. app.php, which creates the application class is loaded afterwards.

**Comment by butonic** [comment]
you can tell oc to load the app.php earlier by adding
```xml
	<types>
		<authentication/>
	</types>
```
to the info.xml. also see https://doc.owncloud.org/server/9.0/developer_manual/app/info.html?highlight=types#types and  https://github.com/owncloud/core/blob/master/apps/user_ldap/appinfo/info.xml#L14

does that solve your problem?

**Comment by ChristophWurst** [comment]
I *think* I tried that already and it didn't work, but I'll check again. Thanks

**Comment by butonic** [comment]
If `authentication` still is not early enough, try `session`

**Comment by ChristophWurst** [comment]
fixed by https://github.com/owncloud/core/pull/25132
