### ISSUE TITLE
Reloading of login screen?

### ISSUE THREAD

**Issue by jas4711** [ChristophWurst/twofactor_totp#19]
If I wait a short while before entering my TOTP code, the app will refresh the HTML page.  Thus losing half of what I typed.  Why is the paged refreshed?  I don't see any reason for doing that.  Related to the TOTP verification window?  You should probably use the time when the OTP was received as a basis for TOTP verification -- and accept 2-3 older OTPs too.

**Comment by ChristophWurst** [comment]
> Why is the paged refreshed?

All I know is that it's not this app that triggers the reload, hence this is a bug in Nextcloud server/ownCloud core. Maybe one of the ajax calls performed in the background trigger the reload.

**Comment by ChristophWurst** [comment]
Please file an issue at https://github.com/nextcloud/server or https://github.com/owncloud/core, depending on what system you observed that behavior.

**Comment by ChristophWurst** [comment]
This was fixed for Nextcloud 11 and Nextcloud 10, see https://github.com/nextcloud/server/pull/984
