### ISSUE TITLE
nextcloud 10 beta TOTP failure

### ISSUE THREAD

**Issue by riegercloud** [ChristophWurst/twofactor_totp#20]
Hi Christoph,
i just installed nextcloud 10 beta (all-inkl.com, PHP 7.08, mysql, apache running on ubuntu) and tried to enable the totp-app using the repository of nextcloud 10 beta. Unfortunately it was not possible. So i had to download the TOTP from github and enabled the app successfully. But now the following errors occurs when trying to enable it for the current user:

![totp](https://cloud.githubusercontent.com/assets/20593693/17050903/c778e9da-4ff5-11e6-91f0-7095dec3a4be.JPG)

The app is currently not usable.

`{"reqId":"V5HUIFUNiiwAAHWLXYUAAAAC","remoteAddr":"193.30.37.163","app":"PHP","message":"include_once(\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/apps\/twofactor_totp\/appinfo\/..\/vendor\/autoload.php): failed to open stream: No such file or directory at \/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/apps\/twofactor_totp\/appinfo\/app.php#24","level":3,"time":"2016-07-22T10:06:56+02:00","method":"GET","url":"\/index.php\/settings\/admin\/log\/entries?offset=13&count=10","user":"cloudchef"}
{"reqId":"V5HUIFUNiiwAAHWLXYUAAAAC","remoteAddr":"193.30.37.163","app":"PHP","message":"include_once(): Failed opening '\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/apps\/twofactor_totp\/appinfo\/..\/vendor\/autoload.php' for inclusion (include_path='\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty\/pear\/console_getopt:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty\/pear\/pear_exception:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty\/pear\/pear-core-minimal\/src:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty\/pear\/archive_tar:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/lib\/private:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/config:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/3rdparty:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/apps:.:\/usr\/share\/php:..:\/www\/htdocs\/<anonymous>\/nc10.c-rieger.de') at \/www\/htdocs\/<anonymous>\/nc10.c-rieger.de\/apps\/twofactor_totp\/appinfo\/app.php#24","level":3,"time":"2016-07-22T10:06:56+02:00","method":"GET","url":"\/index.php\/settings\/admin\/log\/entries?offset=13&count=10","user":"cloudchef"}`

If you are interested i can provide you an access to this nextcloud installation?

Cheers, Carsten

**Comment by ChristophWurst** [comment]
Hi Carsten,

how did you install this app? I guess you've used a git clone, which does not work unless you install the PHP dependencies accordingly with composer.

**Comment by riegercloud** [comment]
Hi Christoph,
grrrhhh - you're right, sorry ;-( 
Actually I do not have ssh access to my domain so i will complete it in the evening and will send an update.
Cheers, Carsten

**Comment by ChristophWurst** [comment]
No worries :-)

You have two options:

1. use the git cone and [install the composer dependencies](https://github.com/ChristophWurst/twofactor_totp/blob/853a39ad11123e264eecb7a4cb8f95abec12f230/Makefile#L22) with `make install-composer-deps`
1. use a [packaged release](https://github.com/ChristophWurst/twofactor_totp/releases)

**Comment by riegercloud** [comment]
Many thanks - now it works
Sorry for my faults!
