### ISSUE TITLE
OC 9.1: Nothing happens when enabling TOTP

### ISSUE THREAD

**Issue by zkvvoob** [ChristophWurst/twofactor_totp#21]
Hi,

I just finished upgrading my OC to v. 9.1 stable. I've installed TwoFactor TOTP from GitHub (I couldn't do it from the appstore inside OC because the version in info.xml was reportedly different than the one in the store).

When I go to Personal settings and click Enable TOTP nothing happens. I don't see a QR code or anything else. Tried both Chrome and Firefox, no Ad-blocking software enabled.

Ubuntu 14.04
PHP 5.6.23

What am I missing?

Thanks!

**Comment by ChristophWurst** [comment]
> I've installed TwoFactor TOTP from GitHub

Did you use a git clone or did you download a release from the release page?

**Comment by ChristophWurst** [comment]
> I couldn't do it from the appstore inside OC because the version in info.xml was reportedly different than the one in the store

I just fixed that. The appstore was set to ``0.3`` instead of ``0.3.0``.

**Comment by zkvvoob** [comment]
Thank you, Christoph. It was my fault, I had simply downloaded a zip from Github, and not a release. The app is working splendidly so far.
