### ISSUE TITLE
Uncaught TypeError: Cannot read property 'View' of undefined

### ISSUE THREAD

**Issue by jaylik** [ChristophWurst/twofactor_totp#23]
Any ideas what could cause this,
```
e428476….js:982Uncaught TypeError: Cannot read property 'View' of undefined
Failed to parse SourceMap: https://xxx/assets/jquery.min.map;
```
...on personal profile page when app is enabled.

**Comment by ChristophWurst** [comment]
Where did you install the app from? Which ownCloud/Nextcloud version are you using?

**Comment by ChristophWurst** [comment]
> e428476….js:982Uncaught

would be good to know the actual file name :-)

**Comment by jaylik** [comment]
That was output from Chrome js debug console. First tried to install current master from github (which was compiled when deployed) and then removed app && dl from owncloud.com.

**Comment by ChristophWurst** [comment]
> That was output from Chrome js debug console.

Please tell me which file and line number the error was thrown.

**Comment by jaylik** [comment]
Don't know about the internals of js parsing but that file seems to have everything merged.

Line 982 (d=a.View.extend...):
`(function(e,a,o,n){'use strict';e.Settings=e.Settings||{};e.Settings.TwoFactorTotp=e.Settings.TwoFactorTotp||{};var i='<div>    <input type="checkbox" class="checkbox" id="totp-enabled">    <label for="totp-enabled">'+t('twofactor_totp','Enable TOTP')+'</label></div>{{#if secret}}<div>    <span>'+t('twofactor_totp','This is your new TOTP secret:')+' {{secret}}</span></div><div>    <span>'+t('twofactor_totp','Scan this QR code with your TOTP app')+'<span><br>    <img src="{{qr}}">    </div>{{/if}}',d=a.View.extend({template:o.compile(i),_loading:undefined,_enabled:undefined,events:{'change #totp-enabled':'_onToggleEnabled'},initialize:function(){this._load()},render:function(t){this.$el.html(this.template(t))},_load:function(){this._loading=!0;var o=e.generateUrl('/apps/twofactor_totp/settings/state'),a=n.ajax(o,{method:'GET',});var t=this;n.when(a).done(function(e){t._enabled=e.enabled;t.$('#totp-enabled').attr('checked',e.enabled)});n.when(a).always(function(){t._loading=!1})},_onToggleEnabled:function(){if(this._loading){return};var a=this.$('#totp-enabled').is(':checked');if(a!==this._enabled){this._loading=!0;var i=e.generateUrl('/apps/twofactor_totp/settings/enable'),o=n.ajax(i,{method:'POST',data:{state:a}});var t=this;n.when(o).done(function(e){t._enabled=e.enabled;t._showQr(e);t.$('#totp-enabled').attr('checked',e.enabled)});n.when(o).always(function(){t._loading=!1});this._enabled=a}},_showQr:function(t){this.render({secret:t.secret,qr:t.qr})}});e.Settings.TwoFactorTotp.View=d})(OC,Backbone,Handlebars,$);;`

Line 983:
`(function(t){'use strict';t.Settings=t.Settings||{};t.Settings.TwoFactorTotp=t.Settings.TwoFactorTotp||{};$(function(){var o=new t.Settings.TwoFactorTotp.View({el:$('#twofactor-totp-settings')});o.render()})})(OC);;`

**Comment by jaylik** [comment]
It seems that this breaks it,
`  'asset-pipeline.enabled' => true,`
...when `false` plugin seems to be working.

**Comment by ChristophWurst** [comment]
from https://github.com/nextcloud/server/pull/418

> The asset pipeline has shown to do more harm than good. Some apps fail
hard with it. Also it makes sure that you download a huge file on each
unvisited page.

So the solution is to disable the asset pipeline.
