### ISSUE TITLE
/login/challenge/totp reloading every 5 sec

### ISSUE THREAD

**Issue by jaylik** [ChristophWurst/twofactor_totp#24]
Don't know if this is Owncloud or plugin issue but page is refreshed every 5 sec and its hard to type the token with mobile devices.

**Comment by tribut** [comment]
Duplicate of #19

**Comment by ChristophWurst** [comment]
This was fixed for Nextcloud 11 and Nextcloud 10, see https://github.com/nextcloud/server/pull/984
