### ISSUE TITLE
Backup-Codes

### ISSUE THREAD

**Issue by mar1u5** [ChristophWurst/twofactor_totp#27]
If you lost your TOTP-device you are in trouble ... I think it would be nice, to have 2-3 codes you can print or write down to a piece of paper in case you cannot use TOTP. Google does this already:

https://support.google.com/accounts/answer/1187538?hl=en

**Comment by ChristophWurst** [comment]
Yes, that makes a lot of sense. However, the Nextcloud server/ownCloud core should provide that functionality as those backup codes are useful for any kind of second factor. Please open an enhancement for that in the appropriate issue tracker. Thanks :rocket:
