### ISSUE TITLE
An error occured while verifying the token

### ISSUE THREAD

**Issue by geekcomputing** [ChristophWurst/twofactor_totp#28]
Using Google Authenticator displays the below error after entering verification code.

**An error occured while verifying the token**

OwnCloud throws below PHP error:

include_once(/var/www/html/owncloud/apps/twofactor_totp/appinfo../vendor/autoload.php): failed to open stream: No such file or directory at /var/www/html/owncloud/apps/twofactor_totp/appinfo/app.php#25

**PHP Version: PHP 5.6.24
OS: CentOS Linux release 7.2.1511 (Core) 
OwnCloud Version: 9.1.0 (stable)**

Any help troubleshooting this would be greatly appreciated.

**Comment by ChristophWurst** [comment]
Hi!
You haven't built the app, hence dependencies are missing. Either use a packaged version (GitHub release page or OC app store) or install composer deps properly. A git clone is not intended to work out of the box. Thx

**Comment by ChristophWurst** [comment]
Hi!
You haven't built the app, hence dependencies are missing. Either use a packaged version (GitHub release page or OC app store) or install composer deps properly. A git clone is not intended to work out of the box. Thx
