### ISSUE TITLE
Reloads every 5 seconds

### ISSUE THREAD

**Issue by hakong** [ChristophWurst/twofactor_totp#29]
Why does it reload the page every 5 seconds when I'm typing in the code? It's quite annoying.

**Comment by ChristophWurst** [comment]
That is not an issue of this app, but the oc core. Report an issue there or simply fix it and open a pull request if is that annoying to you ;-)

**Comment by ChristophWurst** [comment]
@hakong could you please tell me which version of the notifications app you've got? https://github.com/nextcloud/notifications/commit/6d3f3824656581d385769290cfffa1566780bbda should fix that bug.

**Comment by hakong** [comment]
Notifications  0.3.0
ownCloud 9.1.0 (stable)

**Comment by ChristophWurst** [comment]
This was fixed for Nextcloud 11 and Nextcloud 10, see https://github.com/nextcloud/server/pull/984

**Comment by ChristophWurst** [comment]
Fix for oc can be found in https://github.com/owncloud/core/pull/25893

**Comment by hakong** [comment]
Thanks :smile:
