### ISSUE TITLE
Add instance name (e.g. mycloud.mydomain.se) to QR code label

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/twofactor_totp#3]
will help distinguish between different oc instances

**Comment by jas4711** [comment]
The URL and username would help here.  I have several Google/etc accounts and their QR code labels looks like 'Google:foo@bar.com'.  GitHub uses 'github.com/jas4711'.

I think a label like 'username@foo.bar.com/owncloud' would be fine.  No need to include the 'https://' part, but if http or non-standard ports are used I reckon it is needed to differentiate it.

**Comment by mar1u5** [comment]
Maybe we could also take the name from the Nextcloud Theming app (in case it is Nextcloud - in all other cases we could take the `username@foo.bar.com/xcloud` as fallback :wink:)
