### ISSUE TITLE
Next Cloud

### ISSUE THREAD

**Issue by sandbergcs** [ChristophWurst/twofactor_totp#30]
Hello,

I am trying to set up two factor authentication with nextcloud.  The download I have is from owncloud.  But it looks like it will work with both.  When I try and enable the app I get an error because it is looking for owncloud. 9.1 not nextcloud.  Is there a different zip file that I need to make it work?

Thanks,
Chris

**Comment by ChristophWurst** [comment]
Hi! Which version of NC are you running? This app should work with NC10

**Comment by sandbergcs** [comment]
Oh, I am running 9.1.  I dont think I can run NC10 because it is in beta.  From the screenshots it looked like it was 9.1.  Also doesnt NC10 have two factor built in?

**Comment by ChristophWurst** [comment]
> Oh, I am running 9.1

There's no NC 9.1. Either you run the latest NC release, which is 9, or you're using the beta, which is 10.

> Also doesnt NC10 have two factor built in?

Yes and no. NC10 and OC9.1 have a 2FA-framework built-in, where apps can register as 2FA providers. This app is also a simple 2FA provider for that framework.

**Comment by ChristophWurst** [comment]
So please check which exact version you're running. Take a look at the admin page, it should tell you the version.

**Comment by sandbergcs** [comment]
Version

Nextcloud 9.0.53 (stable)
Developed by the Nextcloud community, the source code is licensed under the AGPL.

**Comment by sandbergcs** [comment]
In the screen shots you provided for setting it up, it shows 9.1 so I think thats why I thought I was on 9.1 cause I was on the latest release.

**Comment by ChristophWurst** [comment]
I see. I've use the development version, hence the version number scheme might differ from releases

**Comment by ChristophWurst** [comment]
> Nextcloud 9.0.53 (stable)

You shouldn't get an error then. Please post the exact error message and content of your error log, thanks.

**Comment by sandbergcs** [comment]
![nextclout_tf](https://cloud.githubusercontent.com/assets/20914168/17530490/a0a37380-5e2c-11e6-9584-c743f1058b86.jpg)

**Comment by sandbergcs** [comment]
I am pretty sure its because I grabbed it from apps.owncloud but I thought it would work for both.

**Comment by sandbergcs** [comment]
Is there a different file set that I need?  I am trying to use nextcloud in a HIPAA environment and we cant use 10 until its production.

**Comment by ChristophWurst** [comment]
> Is there a different file set

What do you mean?

**Comment by sandbergcs** [comment]
Because of the error that I attached, says owncloud 9.1 or higher is required.  Something has to be telling nextcloud that its an owncloud app or something.

**Comment by ChristophWurst** [comment]
> Something has to be telling nextcloud that its an owncloud app or something.

Why? OC9.1 apps work on NC *out of the box*, there's currently nothing that needs to be changed in terms of compatibility of oc/nc apps. NC10 is basically an enhanced OC9.1.

**Comment by ChristophWurst** [comment]
So the real problem is that you're running a version of NC that is too old, as 9.1 is the minimum version this app requires -> not a bug
