### ISSUE TITLE
PHP Invalid Argument supplied for foreach() at

### ISSUE THREAD

**Issue by bitking** [ChristophWurst/twofactor_totp#31]
Thanks for making this app but i still get some php errors in my admin console although its working.

Any clue as to how this can happen?

I am using the following setup:
Ubuntu 14.04.3 LTS
Owncloud 9.1.0

----------
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/lib/private/Authentication/TwoFactorAuth/Manager.php#112	2016-07-21T12:30:01+00:00
Error	PHP	Undefined index: two-factor-providers at /var/www/owncloud/lib/private/Authentication/TwoFactorAuth/Manager.php#111	2016-07-21T12:30:01+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/lib/private/Authentication/TwoFactorAuth/Manager.php#112	2016-07-21T12:29:59+00:00
Error	PHP	Undefined index: two-factor-providers at /var/www/owncloud/lib/private/Authentication/TwoFactorAuth/Manager.php#111	2016-07-21T12:30:05+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/lib/private/Authentication/TwoFactorAuth/Manager.php#112

**Comment by ChristophWurst** [comment]
Hi!

This has been fixed for Nextcloud 10 and Nextcloud 11, see https://github.com/nextcloud/server/pull/534 and https://github.com/nextcloud/server/pull/756.

**Comment by bitking** [comment]
uh?and what about owncloud 9.1?

**Comment by ChristophWurst** [comment]
Don't worry, it's fixed in OC too. See https://github.com/owncloud/core/pull/25605 and https://github.com/owncloud/core/pull/25606 :wink:
