### ISSUE TITLE
Credential name again

### ISSUE THREAD

**Issue by jas4711** [ChristophWurst/twofactor_totp#36]
Thanks for improving the credential name.  There might still be room for improvement though.  In 0.4.0 the credential name looks like:

https://moln.sjd.se/owncloud/ (ownCloud):jas@moln.sjd.se/owncloud

Some other credentials I have look like this:

DigitalOcean:simon
Dropbox:simon@josefsson.org
github.com/jas4711
GitLab:simon@josefsson.org
Google:simon@josefsson.org
LinodeManager:simon@josefsson.org
RIPE NCC:simon@josefsson.org

While there appear to be no de-facto naming standard, it looks like a short keyword followed by colon followed by account info is "winning".

How about using the following naming scheme?

ownCloud: jas@moln.sjd.se/owncloud

Where obviously 'jas' is the username and 'moln.sjd.se' is the ownCloud server hostname, and '/owncloud' is the search path.  Non-standard ports or non-https protocols is a complication, but maybe not worth worrying about?  There is no way of knowing that port 443 and port 2382 on the same server doesn't go to the same ownCloud database anyway.

**Comment by ChristophWurst** [comment]
Ok, makes sense. So we'd take the product name (ownCloud/Nextcloud/whatever branded name) as issuer and the cloud id as label, right?

**Comment by jas4711** [comment]
Also according to this link

https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label

you may not use colon (":") in the string except as separator.  Now there are two colons which confuses some apps -- might explain #37

**Comment by jas4711** [comment]
Btw, github changed their credential name to 'GitHub: github.com/jas4711'.  I still have some non-conformant identifiers, but the 'shortname: userinfo' style appears to be winning.
