### ISSUE TITLE
Invaild Barcode Error

### ISSUE THREAD

**Issue by mar1u5** [ChristophWurst/twofactor_totp#37]
Ok ... It seems that there is a bug with the QR-code since 0.4 😒 I've tested you PR ... but ... Yeah 😢 

`Invaild Barcode: otpauth://totp/marius@cloud.domain.com?secret=XXXXXXXXXX&issuer=http://cloud.domain.com/ (Nextcloud)" is no vaild barcode`

Tested with Authy and Google Authentificator 😁 ... Manually typing in the secret works.

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
> Invaild Barcode: otpauth://totp/marius@cloud.domain.com?secret=XXXXXXXXXX&issuer=http://cloud.domain.com/ (Nextcloud)" is no vaild barcode

Hm, that should not happen. I'm encoding those stings with `rawurlencode` here https://github.com/ChristophWurst/twofactor_totp/blob/2ed3b447598aa8c678f6871ff37be8c88d42e019/lib/Controller/SettingsController.php#L111, so it should be encoded in theory…

**Comment by ChristophWurst** [comment]
0.4 works for me with Google Authenticator and the [OTP Authenticator](https://github.com/0xbb/otp-authenticator) – no issues on my instance

**Comment by mar1u5** [comment]
with Nextcloud 10.0 RC1?

**Comment by ChristophWurst** [comment]
with oc9.1

**Comment by ChristophWurst** [comment]
Could also successfully test 0.4 with the current NC server master

**Comment by GhostPunk** [comment]
It's the same error for me. I've just downloaded 0.4 release from here, enabled the app (OC 9.1), went to personal settings, enable two-factor for my account, tried to scan barcode.

Note: I see my full federated account address in the barcode error message, however if I enter my secret manually into Google Authenticator I just need to give my local OC account, and it works.

How can I help you debug this?

**Comment by ChristophWurst** [comment]
> How can I help you debug this?

Could you post a screenshot of an invalid QR code?

**Comment by ChristophWurst** [comment]
Found it, I've used `rawurldecode` instead of `rawurlencode` https://github.com/ChristophWurst/twofactor_totp/blob/8eca1cc845375a367f791ac65d14de793fe44547/lib/Controller/SettingsController.php#L105.

**Comment by ChristophWurst** [comment]
@mar1u5 @GhostPunk please test https://github.com/ChristophWurst/twofactor_totp/releases/tag/0.4.1 and tell me if it works for you, then I'll upload it to the app store. Thanks :rocket:
