### ISSUE TITLE
Disable or Option to Disable Auto Refresh on 2FA Screen

### ISSUE THREAD

**Issue by fahidsh** [ChristophWurst/twofactor_totp#45]
Hi,
Thanks a lot for the great work.
I am using your plugin with Google authenticator and is it working great. only problem I see is that when I login with username and password and it comes to the step where 2FA is presented. page keep refreshing after 6-8 seconds, that is not working well, can I somehow turn off this auto page refresh? I am slow with keyboard. sometimes it takes me a minute or even two struggling with 2FA, because before I can type the 2FA challenge code and login, page refreshes itself again and again.

So even though this app/plugin is something I like a lot, it is just like a buggy app I would somedaz like to see working as it should.

In terms of Security it (2FA page auto refresh) doesn't make any sense, because no other web/app (that uses 2FA) need that and they are all fine.

But still if you do think like that then please include a setting option to Enable/ Disable the auto refresh option.

**Comment by fahidsh** [comment]
here is a little screen-record showing my problem
https://www.youtube.com/watch?v=TfESFWkD0ps

**Comment by ChristophWurst** [comment]
Hi!
Thanks for your thorough report. This is not intendet and a bug of the ownCloud core/Nextcloud server. Good news: it has been fixed already - see issue #29 ;-)
