### ISSUE TITLE
Disable TOTP for remote.php (CalDAV/CardDAV)

### ISSUE THREAD

**Issue by sstolz84** [ChristophWurst/twofactor_totp#46]
Is it possible to deactivate 2FA for the remote.php Interface?
I am using CardDAV and CalDAV on my iPhone and with 2FA activated i get
wrong password messages each time i want to access my calendar and contacts.

After disabling the 2fa for the user, it works again...

**Comment by ChristophWurst** [comment]
Hi @sstolz84,

no. That is impossible by design. Simply generate an app password on your personal setttings and use that as password for your DAV client application, then everything should work again :rocket:
