### ISSUE TITLE
QR not accepted

### ISSUE THREAD

**Issue by MajorCGN** [ChristophWurst/twofactor_totp#47]
Hi,

I can get no authenticator app on iOS to "understand" the QR code generated by TOTP with Nextcloud 10.

I tried different apps, Google Authenticator, HDE OTP - everyone "reads" the QR, but says it has errors.
The generated secret is accepted by every of those apps, when entered manually.

So i tried the example QR on this site - and THAT worked. But as i see, there is much more encoded in the "newer" QR. The easy URL from the example is okay, the longer one can not be parsed by all apps it tested.

The old QR was type Weblink and like that scheme:
otpauth://totp/ownCloud/%20TOTP/secret=BLAHBLAHSECRET
That one is accepted by apps.

The new QR is type text and that scheme:
otpauth://totp/USERNAME@CloudURL/nextcloud?secret=BLAHBLAHSECRET&issuer=CLOUDURI
No way on any app tested.

May be an issue with the type of the QR ?

**Comment by ChristophWurst** [comment]
There was a bug with URI encoding that was fixed in 0.4.1. You can find the release here https://github.com/ChristophWurst/twofactor_totp/releases/tag/0.4.1, but I'll upload it to the app store soon, too.

**Comment by ChristophWurst** [comment]
dup of https://github.com/ChristophWurst/twofactor_totp/issues/37

**Comment by MajorCGN** [comment]
That did it. 
Installed from Appstore, but manually updated to 0.4.1 and that worked :)

Thanks !
