### ISSUE TITLE
Short cookie validity?

### ISSUE THREAD

**Issue by zkvvoob** [ChristophWurst/twofactor_totp#49]
Hello,

First of all - love your app! Been using it with OC 9.1 for a month now. Two things which I'm not really sure whether they're problem with the TOTP app or a core issue:

1. Would it be possible to add a check not to ask for a code again on that computer (i.e. "Remember computer")?
2. Can the TOTP field automatically appear after entering one's credentials (i.e. skip the select authentication page and go directly to the TOTP prompt)?

Thanks!

**Comment by ChristophWurst** [comment]
> Would it be possible to add a check not to ask for a code again on that computer (i.e. "Remember computer")?

AFAIK there are some minor problems with the remember me functionality in oc/nc. Once that has been fixed, you shouldn't have to log in that often. If you manually log in and out, there are no plans to not ask the user to solve the second factor. cc @LukasReschke

> Can the TOTP field automatically appear after entering one's credentials (i.e. skip the select authentication page and go directly to the TOTP prompt)?

Yes, would be possible. That would be an enhancement of OC, so please open an enhancement issue at their core repository.

Thanks for your feedback!
