### ISSUE TITLE
Constant refreshing at OTP screen

### ISSUE THREAD

**Issue by mikerockett** [ChristophWurst/twofactor_totp#50]
As mentioned on the OC app store thread for this app (and elsewhere), the OTP page keeps refreshing. Why does it it need to do this, and why is it so quick?

**Edit:** I'm on NC10, and @ChristophWurst states in #29 that NC10-11 have fixed this in terms of nextcloud/server#984... But it's still refreshing for me, and this was a clean-install.

**Comment by ChristophWurst** [comment]
> Edit: I'm on NC10, and @ChristophWurst states in #29 that NC10-11 have fixed this in terms of nextcloud/server#984... But it's still refreshing for me, and this was a clean-install.

It was fixed *after* the NC10 release, hence the fix will come with the first maintenance release of NC10.

I know this bug is annoying as hell, but there is nothing I can do about it in this app :worried:

**Comment by mikerockett** [comment]
Ah, right - thanks for the clarification. Skipping this for now then.
