### ISSUE TITLE
OC 9.1 Only headline showing, not tick box nor QR code

### ISSUE THREAD

**Issue by sorenweber** [ChristophWurst/twofactor_totp#51]
Hi,

I have downloaded version 0.4.0 from appstore and unpacked in `/var/www/owncloud/apps/twofactor_totp/`

On my user page, I only see the headline. The language is Danish. I looked at the source of the page and I saw only this:
`
<div id="totp-to-faktor-godkendelse">
<div class="section">
    <h2>TOTP To-faktor godkendelse</h2>
    <div id="twofactor-totp-settings"></div>
</div>
</div>
`

There are no errors in the log (set to include everything).

Is it my language, or am I missing some packages?

I run
- Ubuntu Server 14.04
- PHP 5.5.9-1ubuntu4.19
- ownCloud 9.1.0

**Comment by ChristophWurst** [comment]
> I have downloaded version 0.4.0

Please try to update to 0.4.1, which I just uploaded to the app store: https://apps.owncloud.com/content/show.php?content=174726. 

> On my user page, I only see the headline. The language is Danish. I looked at the source of the page and I saw only this:

Could you temporarily change the language (e.g. to English) and check again?

**Comment by sorenweber** [comment]
Sadly, updating to 0.4.1 and changing language to English did not help.

Also, when `twofactor_totp` is enabled the "Sessions" and "App passwords" section do not finish loading (they show the large "loading"-circle fronzen). Disabling `twofactor_totp` allows me to see the sessions and app passwords lists.

**Comment by ChristophWurst** [comment]
Please follow https://doc.owncloud.org/server/9.0/developer_manual/general/devenv.html#enabling-debug-mode and enable debug mode. Then try to reproduce the error and check your browser's development console. I suspect there might be js errors

**Comment by sorenweber** [comment]
I'm not used to debugging in the browser, but I enabled debug mode, opened Firefox developer tools, debugging, JS. I saw these two errors:

`TypeError: a is undefined
<anonymous>
9191b9a7536f67469d6dab110fc85de6.js:994
<anonymous>
9191b9a7536f67469d6dab110fc85de6.js:994
9191b9a7536f67469d6dab110fc85de6.js:994:504

TypeError: $(...).showPassword is not a function
<anonymous>
9191b9a7536f67469d6dab110fc85de6.js:911
n.Callbacks/j()
9191b9a7536f67469d6dab110fc85de6.js:2
n.Callbacks/k.fireWith()
9191b9a7536f67469d6dab110fc85de6.js:2
.ready()
9191b9a7536f67469d6dab110fc85de6.js:2
I()
9191b9a7536f67469d6dab110fc85de6.js:2
9191b9a7536f67469d6dab110fc85de6.js:911:92
`

Is this helpful?

**Comment by ChristophWurst** [comment]
Could you please post your config? Either run ``php occ config:list`` or copy the content of ``config/config.php`` (remove sensitive information).

> Is this helpful?

Unfortunately no.

**Comment by ChristophWurst** [comment]
Do you use the oc *asset pipeline*?

**Comment by sorenweber** [comment]
Yes, I use the asset pipeline. I have just disabled it, and **now your app is working!**

I will leave it disabled. I am not sure if it is beneficial or not.

**Comment by ChristophWurst** [comment]
\o/ nice!

The asset pipeline has proven to be :hankey:, therefore it was removed in Nextcloud. See https://github.com/nextcloud/server/pull/418

**Comment by sorenweber** [comment]
Thanks for you help Christoph!

As an added bonus, disabling asset pipeline suddenly made my owncloud web-interface 5-10 faster!

**Comment by ChristophWurst** [comment]
> As an added bonus, disabling asset pipeline suddenly made my owncloud web-interface 5-10 faster!

hehe, that's great :rocket:
