### ISSUE TITLE
Redirect after login with TOTP

### ISSUE THREAD

**Issue by nextgen-networks** [ChristophWurst/twofactor_totp#52]
It would be fantastic if TOTP checks if an alternate app is configured in ownCloud/nextcloud config als "default" app and redirects to it instead of an hardcoded redirect to the files app.

Thanks for your great work!

Ralf

**Comment by ChristophWurst** [comment]
Hi @nextgen-networks,
this is a bug in the Nextcloud server. https://github.com/nextcloud/server/pull/1188 fixes this problem, pleas help us test the fix, thanks :-)

**Comment by ajdunevent** [comment]
I was just coming by to report this.  Glad it's already being addressed!  Thanks for your awesome work on TOTP, @ChristophWurst!

**Comment by xraMsamohT** [comment]
The fix works. Thank you, @ChristophWurst!

PS: Thanks for this great app!
