### ISSUE TITLE
Restoring access

### ISSUE THREAD

**Issue by InQuize** [ChristophWurst/twofactor_totp#53]
How would one manually restore access to an admin account protected by lost TOTP app? (In theory)
In other words: where is the "on/off switch" for twofactor_totp for a particular account in the NextCloud backend?

**Comment by InQuize** [comment]
The way I found is to delete entry for that user in `oc_twofactor_totp_secrets` table in `nextcloud` database.
Is that ok or am I missing something and there is a more graceful way?

**Comment by InQuize** [comment]
https://github.com/owncloud/core/pull/24559#issuecomment-219960793

**Comment by ChristophWurst** [comment]
Hi,

exactly. Either you use the occ command, or you use an alternative factor. In case you've upgraded to Nextcloud, there will be an option to generate backup codes soon. See https://github.com/nextcloud/server/pull/1171

**Comment by ChristophWurst** [comment]
> The way I found is to delete entry for that user in oc_twofactor_totp_secrets table in nextcloud database.
> Is that ok or am I missing something and there is a more graceful way?

Hacky, but that should fix it. Note that there's a bug in ownCloud that will cause an infinite redirect loop, hence you are caught in the login process and have to manually clear the session cookies.

**Comment by InQuize** [comment]
> Note that there's a bug in ownCloud that will cause an infinite redirect loop, hence you are caught in the login process and have to manually clear the session cookies.

Yes, I encountered that, but it was very easy to fix by deleting cookies for nextcloud domain in `chrome://settings/cookies`
