### ISSUE TITLE
FR: Backup Codes

### ISSUE THREAD

**Issue by Myatu** [ChristophWurst/twofactor_totp#54]
I didn't see this anywhere obvious, so if it is already available, ignore me :)  But can we have a small set (say 3 or 5) backup codes that can be used in case the person does not have the ability to use their authentication app (ie., lost device)?

**Comment by ChristophWurst** [comment]
sure, will be available with Nextcloud 11 https://github.com/nextcloud/server/pull/1171 ;-)
