### ISSUE TITLE
TOTP breaks any client software

### ISSUE THREAD

**Issue by ET-Bent** [ChristophWurst/twofactor_totp#55]
When using this app, you are **not able to log in using any client software** (including Nextclouds Android app). This limits Nextcloud to be used within the browser solely. Using a client shows you this (or something similar):

![owncloud verbindungsassistent_765](https://cloud.githubusercontent.com/assets/5788982/18251023/fd6caee6-7386-11e6-8151-4b8bfb399cd4.png)

After disabling the app everything is back working and you can log in again.

Would it be possible to add a method to generate per-app passwords similar to [Googles 2FA approach](https://support.google.com/mail/answer/185833?hl=en)?

**Comment by ChristophWurst** [comment]
Hi @ET-Bent,

this is fully intended. 2FA disables (sounds better than breaking) password logins, hence clients have to be configured to use app-specific passwords. See the documentation at https://docs.nextcloud.com/server/10/user_manual/session_management.html

> Note

> If two-factor authentication is enabled for your account, device-specific passwords are the only way to configure clients. The client will deny connections of clients using your login password then.

**Comment by rmrfslashbin** [comment]
Thanks for pointing out! Might be worth noting in the twofactor_totp project README.md.

**Comment by ChristophWurst** [comment]
> Thanks for pointing out! Might be worth noting in the twofactor_totp project README.md.

Yes, we could add a small FAQ for that. Wanna add it and open a pull request? ;-)
