### ISSUE TITLE
Does not work with NextCloud 10 (migrated from OwnCloud 9.1) and 0.4.1

### ISSUE THREAD

**Issue by nikolauskrismer** [ChristophWurst/twofactor_totp#56]
Hi,

I just installed NC 10 (migrated from my old OC 9.1) installation and installed your plugin there (using the app functionality of NC itself). The version downloaded is 0.4.1, but I am not getting asked for a second factor.

I activated TOTP for my admin user and after activation I can scan the created QR code (or copy the totp key to my password manager). However, after log out I am not asked for the second factor on login. It just gets me directly to my files after entering the username and password (no totp token is needed at all).

Is there something that I am missing? Do I need to activate the plugin in a second place (maybe activate by user AND in global settings (that I did not find))? What can I do to debug this issue??

Cheers,
Niko

**Comment by ChristophWurst** [comment]
Hi!

Do you have access to your Nextcloud's database? Then please check if an entry was created for your user in `oc_twofactor_totp_secrets`.
The only other situation where 2FA is ignored is when an admin disables 2FA via the occ command line tool. Did you use that maybe to disable 2FA for that user?

**Comment by nikolauskrismer** [comment]
An entry in oc_twofactor_totp_secret has been created, but still NC is not asking for a token.
I did not use occ to disable 2FA for any user (at least not on purpose)... but to be sure: how can I check that?

**Comment by ChristophWurst** [comment]
Strange. Are there any errors in the nextcloud and/or your webserver log?

You can enable 2FA via `php occ twofactorauth:enable <yourusername>`. It shouldn't have any effect if it wasn't disable before.

**Comment by nikolauskrismer** [comment]
I did not find anything in the log files.
However, after calling` php occ twofactorauth:enable <yourusername>` 2FA now works.

Maybe it is a good idea to check for disabled 2FA via command-line when activating it for a user in the frontend (and at least print a warning)...

**Comment by ChristophWurst** [comment]
This is weird. Are you 100% sure you didn't disable 2FA via occ before? :wink: 

FYI https://github.com/nextcloud/server/blob/1d04c9e307892c275f9fad64ef0ebe9bc10e0260/lib/private/Authentication/TwoFactorAuth/Manager.php#L61-L70 is the code that checks whether 2FA should be checked or not.

Is there any way we could reproduce the scenario before? I'm curios why your user was put into that state. Do you maybe have a DB dump that you created during the migration that you could check? It looks like the value for disabling 2FA has been set in the `oc_preferences` table at some point. :confused:

**Comment by ChristophWurst** [comment]
BTW which DB are you using?

**Comment by nikolauskrismer** [comment]
I am using mysql.
And yes... there is a DB dump that I created from OC before switching to NC.

I checked it and there is a 'two_factor_auth_disabled' configkey in the 'oc_preferences' table with configValue '1'.

This is the explanation to everything, but I must have forgotten that I used the occ command with your app in OC before (I tested your app in OC 9.1, but it never worked for me - one reason why I switched to NC - and I was pretty sure that I did not use the occ command in OC with your app, but that's something where I must have been wrong... sry)

Ok... to me the problem is solved. Is there something you want to change (message about the state in the UI) or should I close the issue?

**Comment by ChristophWurst** [comment]
> I checked it and there is a 'two_factor_auth_disabled' configkey in the 'oc_preferences' table with configValue '1'.

Well, then either you ran that command at some point or someone injected it into your DB. Who knows :wink: 

This issue can be closed now since that would have been a general problem with 2FA in the Nextcloud server (the command disables **all** 2FA providers, not only this specific one).

Have fun using the app :rocket: und schöne Grüße nach Tirol
