### ISSUE TITLE
Pin input page is reloading every 5 seconds

### ISSUE THREAD

**Issue by checkelmann** [ChristophWurst/twofactor_totp#57]
First of all, a really good plugin, but I've got an Issue, when i try to Authenticate with my Google Authenticator Pin, the Page is reloading every 5 Seconds.

Installed Nextcloud Version: 10.0.0
Installed Plugin: 0.4.1

There is nothing in the nextcloud log the developer Tools console says

JQMIGRATE: Migrate is installed, version 1.4.0
jquery.min.js?v=ce3e4fa…:4GET https://xxxx/owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json 401 (Unauthorized)send @ jquery.min.js?v=ce3e4fa…:4ajax @ jquery.min.js?v=ce3e4fa…:4fetch @ app.js?v=ce3e4fa…:329initialFetch @ app.js?v=ce3e4fa…:146initialise @ app.js?v=ce3e4fa…:59(anonymous function) @ app.js?v=ce3e4fa…:384j @ jquery.min.js?v=ce3e4fa…:2fireWith @ jquery.min.js?v=ce3e4fa…:2ready @ jquery.min.js?v=ce3e4fa…:2I @ jquery.min.js?v=ce3e4fa…:2
Failed to parse SourceMap: https://xxxx/owncloud/core/vendor/jquery/dist/jquery.min.map

Regards,

Christian

**Comment by ChristophWurst** [comment]
Hi. There was a bug in Nextcloud that caused those reloads, see https://github.com/ChristophWurst/twofactor_totp/issues/19#issuecomment-241344416
