### ISSUE TITLE
Possibility for the admin to show the QR Code

### ISSUE THREAD

**Issue by schannall** [ChristophWurst/twofactor_totp#58]
Hi,
would it be possible for the Administrator to show the QR code of the user? Our employees often fogret their secret...

sC

**Comment by ChristophWurst** [comment]
Starting with NC11, you can also let your users generate backup codes they can use to authenticate if they *forget* their secret. ref https://github.com/nextcloud/server/pull/1171

**Comment by ChristophWurst** [comment]
cc @LukasReschke

**Comment by schannall** [comment]
If the users forget their secret I bet they won't have the secret - or would it be possible for the admin to create the secret?

sC

**Comment by ChristophWurst** [comment]
Which secret? Users will then have TOTP **and** backup codes. That should be enough.

Alternatively, if that kind of 2FA is too complicated for your employees, maybe you should enable an other 2FA provider, like e-mail or SMS.

**Comment by ChristophWurst** [comment]
I'm curious, how do your employees *lose* their TOTP secret? Do they lose their phone? Or uninstall the app?

**Comment by schannall** [comment]
Mostly new phones (as most users use Google Authenticator). Most users only have one software token (most are hardware). I doubt our employees will save their backup code.
I just need a way to restore the token to the users - if I can disable 2fa temoprarily for the users it would also work (if you don't want to store the secrets or give the admin access to them)

sC

**Comment by ChristophWurst** [comment]
> if I can disable 2fa temoprarily for the users it would also work (if you don't want to store the secrets or give the admin access to them)

That's already possible: https://docs.nextcloud.com/server/10/admin_manual/configuration_server/occ_command.html?highlight=occ#two-factor-authentication is your friend ;-)

**Comment by schannall** [comment]
Okay, I guess then it's not really needed. Let's just hope there will be a button in the GUI for that :)
Thanks for your input!

sC

**Comment by ChristophWurst** [comment]
> Let's just hope there will be a button in the GUI for that

Not yet. But feel free to open a feature request in the NC server repo and/or add that button and open a pull request ;-)
