### ISSUE TITLE
Repeated page refresh

### ISSUE THREAD

**Issue by andylampy** [ChristophWurst/twofactor_totp#60]
Hi,

When NextCloud is configured with `'htaccess.RewriteBase' => '/'` which will remove the index.php from the URL, the entry page for the second-factor code will continually refresh every few seconds.

Removing the rewrite will stop this behaviour and allow the verification page to remain on screen without refreshing but is obviously not ideal as the developers say that rewrite should have no adverse impact.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/ChristophWurst/twofactor_totp/issues/19 and will be fixed with the maintenance release 10.0.1. See https://help.nextcloud.com/t/help-testing-the-9-0-54rc1-and-10-0-1rc1/3254 for how you can help testing the RCs
