### ISSUE TITLE
TOTP is not working

### ISSUE THREAD

**Issue by QkiZMR** [ChristophWurst/twofactor_totp#61]
TOTP is not working at all. I enabled TOTP but I dont see any settings in admin page. In my profile I see only this:
![2016-10-01 10_37_34-osobiste - owncloud](https://cloud.githubusercontent.com/assets/7574087/19012930/1f657c94-87c3-11e6-9e0c-adaa8c96a45f.png)
Only header with TOTP text and nothing there.

**Comment by QkiZMR** [comment]
Errors in log:
`{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined variable: usedBackends at \/var\/www\/owncloud.example.com\/apps\/user_otp\/appinfo\/app.php#47","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                                           
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud.example.com\/apps\/user_otp\/lib\/otp.php#86","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                                        
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: backend_type_validated at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#1996","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                            
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: log at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#2494","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                               
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: debug at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#2499","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                             
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: display_log at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#2504","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                       
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: timezone at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#3756","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                                          
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"date_default_timezone_set(): Timezone ID '' is invalid at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#3759","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                             
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Undefined index: encryption_key_full_path at \/var\/www\/owncloud.example.com\/apps\/user_otp\/3rdparty\/multiotp\/multiotp.class.php#1668","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}                                                                                                                                                                          
{"reqId":"2mz2D4Echxhdsq\/4LuXe","remoteAddr":"","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud.example.com\/apps\/user_otp\/lib\/otp.php#214","level":3,"time":"2016-10-01T08:00:32+00:00","method":"--","url":"--","user":"--"}`

**Comment by ChristophWurst** [comment]
`user_otp`? this is another app. Where did you install that one from?

**Comment by QkiZMR** [comment]
Oh, sorry. This was from other app that I tested before TOTP. So ignore that errors. How to enable debug mode in your app?

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/10/developer_manual/general/debugging.html#debug-mode for how to enable debug mode in Nextcloud

**Comment by QkiZMR** [comment]
Why you close issue? Errors that I paste are from other app, so ignore them. Your app doesn't produce any errors, even if I turn debug in ownCloud or even turn error_reporting = E_ALL. Your app is in bundle with ownCloud. I dont have to install separately.  
I enable debug mode but there is no new message in log. TOTP still not working. I change language to English. 
![zaznaczenie_001](https://cloud.githubusercontent.com/assets/7574087/19020252/ce735f90-88a3-11e6-8a58-28e6a6133d11.png)
Any additional actions are needed after enabling TOTP?

**Comment by ChristophWurst** [comment]
How did you install the app? Which version are you using?

**Comment by QkiZMR** [comment]
Like I said before I not installed it manually. It was in ownCloud 9.1.1 already. TOTP is in version 0.4.1.

**Comment by ChristophWurst** [comment]
So where did you get ownCloud from? I just downloaded their .zip and it does not contain this app.

**Comment by QkiZMR** [comment]
From owncloud.org. Then from Apps menu I enable TOTP app. Maybe then app is downloaded and extracted to app directory. So that why I think that was in bundle with ownCloud. Anyway app downloaded from ownCloud app menu is same as downloaded from ownCloud app store https://apps.owncloud.com/

**Comment by ChristophWurst** [comment]
Yup, it was downloaded then. Let me quickly set up ownCloud and try to repoduce your problem…

**Comment by ChristophWurst** [comment]
Works perfectly with a fresh install of oc:
![bildschirmfoto von 2016-10-02 20-34-47](https://cloud.githubusercontent.com/assets/1374172/19022763/bbc75432-88df-11e6-9af4-ed5ab2609d90.png)

**Comment by ChristophWurst** [comment]
Btw. there are no admin settings. Users can enable TOTP via their personal settings

**Comment by QkiZMR** [comment]
I'm trying nextcloud (fresh install) now and also works perfectly. I think I move to nextcloud. Thanks for checking.

**Comment by ChristophWurst** [comment]
> I'm trying nextcloud (fresh install) now and also works perfectly. I think I move to nextcloud. Thanks for checking.

Great! Please report back if you face any other problems with Nextcloud :-)
