### ISSUE TITLE
Two factor screen keep reloading

### ISSUE THREAD

**Issue by ernesst** [ChristophWurst/twofactor_totp#62]
Dear, 

First of all thanks for this great app, I'm currently using it with nextcloud 10. 
I noticed something annoying : 
As soon i've enter my login and pwd, i got the page for the twofactor auth. This one keeps reloading every 5-7 secondes. 
 
Rgds

**Comment by ChristophWurst** [comment]
Hi. There was a bug in Nextcloud that caused those reloads, see https://github.com/ChristophWurst/twofactor_totp/issues/19#issuecomment-241344416. Should be fixed with 10.0.1
