### ISSUE TITLE
Can't enable TOTP on personal site

### ISSUE THREAD

**Issue by nowy1243** [ChristophWurst/twofactor_totp#65]
Hi
I have installed TOTP from github package, turned on globally and sudo -u apache ./occ twofactorauth:enable for user. But when I go to personal setting I can't enable totp. Only blank area. What should I have to check ?

![image](https://cloud.githubusercontent.com/assets/22762278/19260390/66b7bb48-8f89-11e6-8eef-fce5224d748c.png)

**Comment by ChristophWurst** [comment]
Hi,

not sure why, but another user recently reported that this app does not work with ownCloud anymore. Migrating to Nextcloud fixes the problem: https://github.com/ChristophWurst/twofactor_totp/issues/61#issuecomment-250987814

Is there anything in the log after you have enabled the debug mode? https://docs.nextcloud.com/server/10/developer_manual/general/debugging.html#debug-mode

**Comment by nowy1243** [comment]
Hi
I moved service from owncloud to nextcloud and totp works good :)
thank You
