### ISSUE TITLE
twofactor_totp: App Certificate is not valid.

### ISSUE THREAD

**Issue by erjenrijnders** [ChristophWurst/twofactor_totp#67]
Hi,

I use Owncloud 9.1.1 and installed the two factor totp app which is working fine. However, the integrity check gives this error:

> Results
=======
- twofactor_totp
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- App Certificate is not valid.

Raw output
==========
Array
(
    [twofactor_totp] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => App Certificate is not valid.
                )

        )

)

Any idea? Is a new certificate needed?

**Comment by ChristophWurst** [comment]
> Any idea? Is a new certificate needed?

This app is now signed for Nextcloud, therefore it fails on ownCloud.

Let me fix that on the oc app store one more time, but be aware that there won't be any updates of this app for ownCloud in the future. 0.4.1 is the last version that can be used with it.

**Comment by ChristophWurst** [comment]
Should be fixed, but I could not test this as all my instances run Nextcloud.

**Comment by erjenrijnders** [comment]
I have tested it and it works indeed, thanks! 
Thanks for sharing those details, will consider nextcloud then.
