### ISSUE TITLE
Move to ownCloud GitHub org?

### ISSUE THREAD

**Issue by ChristophWurst** [ChristophWurst/twofactor_totp#7]
Does it make sense to move this repo into the ownCloud GitHub organization?

Yes, because…
* we might need it for Transifex? @DeepDiver1975

No, because…
* the more apps we move to the org, the slower Travis (and other services) becomes
* contributions are equally simple as the usual GitHub workflow (fork+PR) works and I can add individual people to this repo if necessary
* people think apps in the org are officially supported (by the Inc), which they mostly aren't. Same for this app (developed in my free time).

cc @PVince81 @DeepDiver1975 opinions/objections on leaving it as is?

**Comment by DeepDiver1975** [comment]
> Yes, because…
> 
>     we might need it for Transifex? @DeepDiver1975

Transifex is also possible outside the org

**Comment by ChristophWurst** [comment]
Awesome, thanks :-)
