### ISSUE TITLE
Template not found.

### ISSUE THREAD

**Issue by jakubfijolek** [ChristophWurst/twofactor_totp#72]
After make and copying files to main owncloud directory i get following error, with 500 status code when trying to access "Personal" tab.

`Exception: {"Exception":"Exception","Message":"template file not found: template:personal","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(198): OC\\Template\\TemplateFileLocator->find('personal')\n#1 \/var\/www\/owncloud\/lib\/private\/legacy\/template.php(85): OC_Template->findTemplate('', 'twofactor_totp', 'personal')\n#2 \/var\/www\/owncloud\/settings\/personal.php(3): OC_Template->__construct('twofactor_totp', 'personal')\n#3 \/var\/www\/owncloud\/lib\/private\/Route\/Route.php(154) : runtime-created function(1): require_once('\/var\/www\/ownclo...')\n#4 [internal function]: __lambda_func()\n#5 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func('\\x00lambda_488', Array)\n#6 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/settings\/perso...')\n#7 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Template\/TemplateFileLocator.php","Line":55}`

I'm running Owncloud 9.1
Tried solution from here [https://github.com/owncloud/core/issues/8071](url) but it does not work.

**Comment by ChristophWurst** [comment]
Hi,
are you planning to contribute to the source code? If you just want to use the app, then please either use the app store or grab a package from here https://github.com/ChristophWurst/twofactor_totp/releases.
Thanks

**Comment by jakubfijolek** [comment]
Hi @ChristophWurst 
I just want to use the app. Thank you for linking releases - works fine (or at least does not throw an error ;) ) 
If i may suggest i think it would be good to add 2-3 steps to deploy your app into owncloud/nextcloud, current Readme is slightly misleading and looks like the only way of using an app is manual make and installation.
